#!/bin/bash

[[ $(screen -list| grep -c 'bot_teste') == '0' ]] && {
    clear
    echo -e "\E[44;1;37m     BOT TESTE  By: @alfalemos    \E[0m"
    echo ""
    echo -ne "\n\033[1;32mINFORME O TOKEN\033[1;37m: "
    read token
    echo ""
    echo -ne "\n\033[1;32mINFORME O LINK DE DOWNLOAD DIRETO DO APP\033[1;37m: "
    read link_apk
    echo ""
    echo -ne "\n\033[1;32mINFORME O TEMPO DE DURAÇÃO DO TESTE (em horas)\033[1;37m: "
    read tempo_teste
    clear
    echo ""
    echo -e "\033[1;32mINICIANDO BOT TESTE \033[0m\n"
    cd $HOME/BOT
    rm -rf $HOME/BOT/botssh.sh
    wget https://gitea.com/alfalemos/SSHPLUS/raw/branch/main/Modulos/botssh.sh >/dev/null 2>&1
    chmod 777 botssh.sh
    echo ""
    sleep 1
    screen -dmS bot_teste ./botssh.sh "$token" "$link_apk" "$tempo_teste" > /dev/null 2>&1
    clear
    echo "BOT ATIVADO COM SUCESSO"
    menu
} || {
    screen -r -S "bot_teste" -X quit
    clear
    echo "BOT DESATIVADO"
    menu
}